import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import pc from 'picocolors';
import { findRepoRoot } from '../git/git-client';
import { resolveRunId, readRunRecord, updateRunRecord } from '../core/run-store';
import { runDir } from '../util/paths';
import { info, success, error, warn, header, divider, kv } from '../util/output';

export interface PrOptions {
  base?: string;
  draft?: boolean;
  title?: string;
}

export async function prCommand(runIdArg: string, opts: PrOptions): Promise<void> {
  const repoRoot = findRepoRoot(process.cwd());
  const runId = resolveRunId(repoRoot, runIdArg);
  const record = readRunRecord(repoRoot, runId);
  const dir = runDir(repoRoot, runId);

  header(`PR: ${runId}`);
  divider();

  // Guard: refuse to PR a rolled-back or still-running run
  if (record.status === 'rolled-back') {
    throw new Error(`Run ${runId} was rolled back — nothing to PR.`);
  }
  if (record.status === 'starting' || record.status === 'running') {
    throw new Error(`Run ${runId} is still in progress.`);
  }
  if (record.prUrl) {
    warn(`PR already exists: ${record.prUrl}`);
    return;
  }

  // Check gh is available
  try {
    execFileSync('gh', ['--version'], { stdio: 'ignore', timeout: 5000 });
  } catch {
    throw new Error(
      'GitHub CLI (gh) not found on PATH.\n' +
      'Install it from https://cli.github.com then run: gh auth login'
    );
  }

  // Push branch to remote
  info(`Pushing branch: ${pc.cyan(record.branchName)}`);
  try {
    execFileSync('git', ['push', '-u', 'origin', record.branchName], {
      cwd: repoRoot,
      stdio: 'inherit',
    });
    success('Branch pushed.');
  } catch (err: any) {
    throw new Error(`Failed to push branch: ${err.message}`);
  }

  // Build PR title and body
  const title = opts.title ?? truncate(record.task, 72);
  const base = opts.base ?? record.baseBranch;

  const summaryPath = path.join(dir, 'summary.md');
  const handoffPath = path.join(dir, 'handoff.md');

  const summaryContent = fs.existsSync(summaryPath)
    ? fs.readFileSync(summaryPath, 'utf-8').trim()
    : '';
  const handoffContent = fs.existsSync(handoffPath)
    ? fs.readFileSync(handoffPath, 'utf-8').trim()
    : '';

  const body = buildPrBody({ record, runId, summary: summaryContent, handoff: handoffContent });

  // Create PR via gh
  info('Creating GitHub PR...');
  const ghArgs = ['pr', 'create', '--title', title, '--body', body, '--base', base];
  if (opts.draft) ghArgs.push('--draft');

  let prUrl: string;
  try {
    prUrl = execFileSync('gh', ghArgs, {
      cwd: repoRoot,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
    }).trim();
  } catch (err: any) {
    const stderr = (err.stderr as string | undefined)?.trim() ?? '';
    throw new Error(`gh pr create failed: ${stderr || err.message}`);
  }

  // Persist PR URL
  updateRunRecord(repoRoot, runId, { prUrl });

  const prJsonPath = path.join(dir, 'pr.json');
  fs.writeFileSync(
    prJsonPath,
    JSON.stringify({ url: prUrl, base, title, createdAt: new Date().toISOString() }, null, 2),
    'utf-8'
  );

  divider();
  success('PR created.');
  console.log('');
  kv('URL', pc.cyan(prUrl));
  kv('Branch', record.branchName);
  kv('Base', base);
  console.log('');
}

function buildPrBody(opts: {
  record: ReturnType<typeof readRunRecord>;
  runId: string;
  summary: string;
  handoff: string;
}): string {
  const { record, runId, summary, handoff } = opts;
  const lines: string[] = [];

  lines.push(`## Task`);
  lines.push(``);
  lines.push(record.task);
  lines.push(``);

  if (summary) {
    lines.push(`## Summary`);
    lines.push(``);
    // Pull out just the Changes section from summary.md to avoid duplication
    const changesMatch = summary.match(/## Changes\n([\s\S]*?)(?:\n## |$)/);
    if (changesMatch) {
      lines.push('```');
      lines.push(changesMatch[1].trim());
      lines.push('```');
    }
    lines.push(``);
  }

  if (handoff) {
    const reviewSection = handoff.match(/## Review Commands\n([\s\S]*?)(?:\n## |$)/);
    // Add the files changed section
    const filesSection = handoff.match(/## Files Modified\n([\s\S]*?)(?:\n## |$)/);
    if (filesSection) {
      lines.push(`## Files Changed`);
      lines.push(``);
      lines.push(filesSection[1].trim());
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by [agentlayer](https://github.com/CalebMorse06/agentlayer-cli) · run \`${runId}\` · provider \`${record.provider}\`*`);

  return lines.join('\n');
}

function truncate(str: string, max: number): string {
  return str.length <= max ? str : str.slice(0, max - 1) + '…';
}
